apiVersion: v1
kind: ConfigMap
metadata:
  name: cryptpad-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptpad.labels" . | nindent 4 }}
data:
  config.js: |
    module.exports = {
        httpUnsafeOrigin: {{ .Values.mainOrigin | quote }},
        httpSafeOrigin: {{ .Values.sandboxOrigin | quote }},
        httpAddress: '0.0.0.0',
        httpPort: 3000,
        websocketPort: 3003,
        adminKeys: [],
        filePath: './datastore/',
        archivePath: './data/archive',
        pinPath: './data/pins',
        taskPath: './data/tasks',
        blockPath: './block',
        blobPath: './blob',
        blobStagingPath: './data/blobstage',
        decreePath: './data/decrees',
        logPath: './data/logs',
        logToStdout: true,
        logLevel: 'info',
        logFeedback: false,
        verbose: false,
        installMethod: 'k8s-docker',
    };
  application_config.js.tmpl: |
    (() => {
    const factory = (AppConfig) => {
        AppConfig.loginSalt = '__LOGIN_SALT__';
        AppConfig.minimumPasswordLength = 8;
        return AppConfig;
    };
    if (typeof(module) !== 'undefined' && module.exports) {
        module.exports = factory(require('../www/common/application_config_internal.js'));
    } else if ((typeof(define) !== 'undefined' && define !== null) && (define.amd !== null)) {
        define(['/common/application_config_internal.js'], factory);
    }
    })();
  {{- if .Values.sso.enabled }}
  sso.js: |
    module.exports = {
      enabled: true,
      enforced: {{ .Values.sso.enforced }},
      cpPassword: true,
      forceCpPassword: true,
      list: [
        {
          name: 'keycloak',
          type: 'oidc',
          url: process.env.SSO_ISSUER_URL,
          client_id: process.env.SSO_CLIENT_ID,
          client_secret: process.env.SSO_CLIENT_SECRET,
          jwt_alg: 'RS256',
          username_scope: 'profile',
          username_claim: 'preferred_username',
          use_pkce: true,
          use_nonce: true
        }
      ]
    };
  {{- end }}
  nginx.conf: |
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;
        client_max_body_size 150m;

        location ^~ /cryptpad_websocket {
            proxy_pass http://127.0.0.1:3003;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_read_timeout 86400s;
        }

        location / {
            proxy_pass http://127.0.0.1:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_read_timeout 86400s;
        }
    }
