apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptpad-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptpad.labels" . | nindent 4 }}
    app.kubernetes.io/component: cryptpad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
