apiVersion: v1
kind: Service
metadata:
  name: cryptpad
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptpad.labels" . | nindent 4 }}
    app.kubernetes.io/component: cryptpad
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cryptpad
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
